### ISSUE TITLE
NPM NOT WORKED PROPERLY AND NOT CREATED NODE MOULUS FOLDER

### ISSUE THREAD

**Issue by rajagupt01** [CypherpunkArmory/UserLAnd#1202]
root@localhost:~/RajaIsLive# npm $internal/RajaIsLive
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /usr/bin/npm:19:21
    at Object.<anonymous> (/usr/bin/npm:153:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by corbinlc** [comment]
Closing as part of a repository cleanup. If this issue is still relevant, feel free to reopen it or file a fresh one.
