### ISSUE TITLE
Android 6.0.1 - crashes always with last update 3.0.0

### ISSUE THREAD

**Issue by marcoratto** [CypherpunkArmory/UserLAnd#1590]
After last update to 3.0.0 version, UserLAnd crashes always on Android 6.0.1

**Comment by marcoratto** [comment]
07-26 10:45:53.661 16393 16393 D AndroidRuntime: Shutting down VM
07-26 10:45:53.665   500  1111 D BandwidthController: [LG DATA] No such appUid: 10105
07-26 10:45:53.666   500  1111 D DnsProxyListener: App 10105 tries DNS query. Accept family:0 protocol:0
07-26 10:45:53.667 16393 16393 E AndroidRuntime: FATAL EXCEPTION: main
07-26 10:45:53.667 16393 16393 E AndroidRuntime: Process: tech.ula, PID: 16393
07-26 10:45:53.667 16393 16393 E AndroidRuntime: java.lang.NoSuchMethodError: No static method stream([Ljava/lang/Object;)Ljava/util/stream/Stream; in class Ljava/util/Arrays; or its super classes (declaration of 'java.util.Arrays' appears in /system/framework/core-libart.jar)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at com.termux.app.ExtraKeyButton.<init>(ExtraKeysInfos.java:316)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at com.termux.app.ExtraKeyButton.<init>(ExtraKeysInfos.java:287)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at com.termux.app.ExtraKeysInfos.<init>(ExtraKeysInfos.java:55)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at com.termux.app.TermuxPreferences.reloadFromProperties(TermuxPreferences.java:208)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at com.termux.app.TermuxPreferences.<init>(TermuxPreferences.java:93)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at com.termux.app.TermuxActivity.onCreate(TermuxActivity.java:209)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6279)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2500)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:163)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5585)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
07-26 10:45:53.667 16393 16393 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
07-26 10:45:53.669  1092  1911 W ActivityManager:   Force finishing activity tech.ula/com.termux.app.TermuxActivity
07-26 10:45:53.673  1092  1911 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
07-26 10:45:53.688  1092  1911 W ActivityManager:   Force finishing activity tech.ula/.library.MainActivity
07-26 10:45:53.693  1092  1121 D PhoneWindowEx: [PWEx][generateLayout] setLGNavigationBarColor : colors=0xff000000
07-26 10:45:53.693  1092  1121 I PhoneWindow: [setLGNavigationBarColor] color=0x ff000000
07-26 10:45:53.702  1834  4108 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:763 android.content.ContextWrapper.sendBroadcast:396 com.lge.mlt.providers.LDBSmartCareTrigger.sendMsgSmartCare:33 com.lge.mlt.providers.LDBMainLogProvider.insert:263 android.content.ContentProvider$Transport.insert:263

**Comment by corbinlc** [comment]
Closing as part of a repository cleanup. If this issue is still relevant, feel free to reopen it or file a fresh one.
