### ISSUE TITLE
Help - npm error : cache issue only on UserLand (Ubuntu & Debian)

### ISSUE THREAD

**Issue by Nostres25** [CypherpunkArmory/UserLAnd#1672]
# Describe the issue you are having.

Hey ! I have installed UserLand on my phone (Galaxy S10) for my discord bot on Debian or Ubuntu. In first time i have tried on Debian. I used curl to install the new versions of nodejs (V16.x) and git. When i send npm install discord.js, installing the latest version of discord.js : i have an error (sceeen). Also with Ubuntu

# Describe how your task behaves in a regular Linux environment
The new versions of discord.js works

- Android: 11
- One UI: 3.1
- UserLand: 3.1.4
- nodejs: 16.19.0
- npm 8.19.3 or 9.4.0
- discord.js: 14.x (tried to install 14.7.1)
- Devian release tested : 10

![Screenshot_20230128-223823_UserLAnd.jpg](https://user-images.githubusercontent.com/76039825/215294630-82306823-0f28-4bf9-8cf3-add5a381da75.jpg)
![Screenshot_20230128-234007_UserLAnd.jpg](https://user-images.githubusercontent.com/76039825/215294643-eff4d797-5717-4c35-a505-9a494d148786.jpg)

Thank-you !

**Comment by Nostres25** [comment]
I have also tested with my Xiaomi redmi note 10s on Android 12 ans with MIUI 13. The firsts package installations (discord.js, fs...) hasard worked but after, i have an error of npm cache installation for all package installations. The error ask to rename a cache file by another path but that don't works.
Same with the canvas package :
```
Error: Command failed: npm install canvas
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /home/userland/.npm/_cacache/tmp/7ac7b354
npm ERR! dest /home/userland/.npm/_cacache/content-v2/sha512/cc/83/8c3aa677d2530fb3b92976fd792a10def5bb1f5dc9b82356acd238d5a40a00c0c35b5aad0a040f0f2e0ca01929f4355275f6a609cc7734ba676b4c15d116
npm ERR! errno ENOENT
npm ERR! enoent Invalid response body while trying to fetch https://registry.npmjs.org/chownr: ENOENT: no such file or directory, rename '/home/userland/.npm/_cacache/tmp/7ac7b354' -> '/home/userland/.npm/_cacache/content-v2/sha512/cc/83/8c3aa677d2530fb3b92976fd792a10def5bb1f5dc9b82356acd238d5a40a00c0c35b5aad0a040f0f2e0ca01929f4355275f6a609cc7734ba676b4c15d116'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/userland/.npm/_logs/2023-02-15T18_53_59_349Z-debug-0.log

    at checkExecSyncError (node:child_process:861:11)
    at Object.execSync (node:child_process:932:15)
    at eval (eval at <anonymous> (/home/userland/bot/uno/index.js:248:21), <anonymous>:1:15)
    at Client.<anonymous> (/home/userland/bot/uno/index.js:248:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by corbinlc** [comment]
Closing as part of a repository cleanup. If this issue is still relevant, feel free to reopen it or file a fresh one.
