### ISSUE TITLE
Hangs on "Downloading required assets" then crashes

### ISSUE THREAD

**Issue by k3an3** [CypherpunkArmory/UserLAnd#47]
I cannot start any sessions. When creating a session and choosing it, the screen displays "Downloading required assets". Nothing changes until Android displays an ANR dialog prompting to kill the app. I have also enabled debug logging and turned up verbosity, but I cannot find this log on the sdcard.

This is a Moto X4 updated to Android 8.1. Will update with more information once I have it.

**Comment by lapsio** [comment]
Did you try to wait for few minutes ignoring dialog? It can take a while and Android sometimes too eagerly prompts to kill apps that don't respond

**Comment by keaneokelley** [comment]
Yes, I have granted storage permissions and endured this in App Info. I have waited about 10 minutes, at which point the app completely crashes (I misspoke, there's no ANR dialog. It crashes back to home screen).

How large is the download?

**Comment by MatthewTighe** [comment]
UserLAnd should not let you get to the download stage without granting storage permissions, but that would cause download failures.

@keaneokelley 
The files are downloaded using the Android download manager. Double check in your notification bar that nothing is happening during the download step. The log file is located at /mnt/sdcard/PRoot_Debug_Log. We were experiencing a bug around the log file during alpha, so the implementation is likely not perfect yet. The download is ~80mb for the largest file.

**Comment by keaneokelley** [comment]
@MatthewTighe I do not see any notifications from the Android download manager, nor is the debug log being created. Here's the logcat when it crashes; seems the files aren't there:

```
06-20 12:09:09.876 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, proot] 
     with env {}
06-20 12:09:09.936 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: proot: No such file or directory
06-20 12:09:09.941 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, proot]
    stdout: chmod: proot: No such file or directory
06-20 12:09:09.944 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, killProcTree.sh] 
     with env {}
06-20 12:09:09.983 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: killProcTree.sh: No such file or directory
06-20 12:09:09.986 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, killProcTree.sh]
    stdout: chmod: killProcTree.sh: No such file or directory
06-20 12:09:09.987 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, isServerInProcTree.sh] 
     with env {}
06-20 12:09:10.006 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: isServerInProcTree.sh: No such file or directory
06-20 12:09:10.007 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, isServerInProcTree.sh]
    stdout: chmod: isServerInProcTree.sh: No such file or directory
06-20 12:09:10.008 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, busybox] 
     with env {}
06-20 12:09:10.026 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: busybox: No such file or directory
06-20 12:09:10.028 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, busybox]
    stdout: chmod: busybox: No such file or directory
06-20 12:09:10.029 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, libtalloc.so.2] 
     with env {}
06-20 12:09:10.045 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: libtalloc.so.2: No such file or directory
06-20 12:09:10.047 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, libtalloc.so.2]
    stdout: chmod: libtalloc.so.2: No such file or directory
06-20 12:09:10.049 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, execInProot.sh] 
     with env {}
06-20 12:09:10.064 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: execInProot.sh: No such file or directory
06-20 12:09:10.065 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, execInProot.sh]
    stdout: chmod: execInProot.sh: No such file or directory
06-20 12:09:10.067 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, startSSHServer.sh] 
     with env {}
06-20 12:09:10.083 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: startSSHServer.sh: No such file or directory
06-20 12:09:10.085 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, startSSHServer.sh]
    stdout: chmod: startSSHServer.sh: No such file or directory
06-20 12:09:10.086 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, startVNCServer.sh] 
     with env {}
06-20 12:09:10.101 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: startVNCServer.sh: No such file or directory
06-20 12:09:10.102 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, startVNCServer.sh]
    stdout: chmod: startVNCServer.sh: No such file or directory
06-20 12:09:10.103 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, startVNCServerStep2.sh] 
     with env {}
06-20 12:09:10.119 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: startVNCServerStep2.sh: No such file or directory
06-20 12:09:10.119 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, startVNCServerStep2.sh]
    stdout: chmod: startVNCServerStep2.sh: No such file or directory
06-20 12:09:10.120 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, busybox] 
     with env {}
06-20 12:09:10.136 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: busybox: No such file or directory
06-20 12:09:10.137 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, busybox]
    stdout: chmod: busybox: No such file or directory
06-20 12:09:10.138 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [chmod, 0777, libdisableselinux.so] 
     with env {}
06-20 12:09:10.153 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: chmod: libdisableselinux.so: No such file or directory
06-20 12:09:10.153 21589-21652/tech.ula E/Exec: Failed to execute command [chmod, 0777, libdisableselinux.so]
    stdout: chmod: libdisableselinux.so: No such file or directory
06-20 12:09:10.170 21589-21652/tech.ula D/EXEC_DEBUG_LOGGER: Running: [../support/busybox, sh, -c, ../support/execInProot.sh /support/extractFilesystem.sh &> /mnt/sdcard/PRoot_Debug_Log] 
     with env {ROOT_PATH=/data/user/0/tech.ula/files, PROOT_DEBUG_LEVEL=9, LD_LIBRARY_PATH=/data/user/0/tech.ula/files/support, ROOTFS_PATH=/data/user/0/tech.ula/files/1}
06-20 12:09:10.324 21589-21589/tech.ula E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.ula, PID: 21589
    java.lang.RuntimeException: java.io.IOException: Cannot run program "../support/busybox" (in directory "/data/user/0/tech.ula/files/1"): error=2, No such file or directory
        at tech.ula.utils.ExecUtility.execLocal(ExecUtility.kt:49)
        at tech.ula.utils.ExecUtility.wrapWithBusyboxAndExecute(ExecUtility.kt:94)
        at tech.ula.utils.ExecUtility.wrapWithBusyboxAndExecute$default(ExecUtility.kt:69)
        at tech.ula.utils.FilesystemUtility.extractFilesystem(FilesystemUtility.kt:18)
        at tech.ula.SessionListActivity$startSession$1$2.doResume(SessionListActivity.kt:346)
        at tech.ula.SessionListActivity$startSession$1$2.invoke(Unknown Source:42)
        at tech.ula.SessionListActivity$startSession$1$2.invoke(SessionListActivity.kt:39)
        at tech.ula.utils.AsyncKt$async$2.doResume(Async.kt:7)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
     Caused by: java.io.IOException: Cannot run program "../support/busybox" (in directory "/data/user/0/tech.ula/files/1"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at tech.ula.utils.ExecUtility.execLocal(ExecUtility.kt:36)
        at tech.ula.utils.ExecUtility.wrapWithBusyboxAndExecute(ExecUtility.kt:94) 
        at tech.ula.utils.ExecUtility.wrapWithBusyboxAndExecute$default(ExecUtility.kt:69) 
        at tech.ula.utils.FilesystemUtility.extractFilesystem(FilesystemUtility.kt:18) 
        at tech.ula.SessionListActivity$startSession$1$2.doResume(SessionListActivity.kt:346) 
        at tech.ula.SessionListActivity$startSession$1$2.invoke(Unknown Source:42) 
        at tech.ula.SessionListActivity$startSession$1$2.invoke(SessionListActivity.kt:39) 
        at tech.ula.utils.AsyncKt$async$2.doResume(Async.kt:7) 
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54) 
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161) 
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25) 
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) 
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285) 
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152) 
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990) 
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938) 
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) 
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:128)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at tech.ula.utils.ExecUtility.execLocal(ExecUtility.kt:36) 
        at tech.ula.utils.ExecUtility.wrapWithBusyboxAndExecute(ExecUtility.kt:94) 
        at tech.ula.utils.ExecUtility.wrapWithBusyboxAndExecute$default(ExecUtility.kt:69) 
        at tech.ula.utils.FilesystemUtility.extractFilesystem(FilesystemUtility.kt:18) 
        at tech.ula.SessionListActivity$startSession$1$2.doResume(SessionListActivity.kt:346) 
        at tech.ula.SessionListActivity$startSession$1$2.invoke(Unknown Source:42) 
        at tech.ula.SessionListActivity$startSession$1$2.invoke(SessionListActivity.kt:39) 
        at tech.ula.utils.AsyncKt$async$2.doResume(Async.kt:7) 
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54) 
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161) 
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25) 
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) 
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285) 
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152) 
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990) 
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938) 
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) 
```

**Comment by keaneokelley** [comment]
Well it started getting past the downloads suddenly, even though I can't see their progress. And the logging does appear to work. I'll do some more testing.

I've got a working session now though.

**Comment by corbinlc** [comment]
It looks like in the case where it failed, it either didn't download the files or failed to move them into the correct directories for use.  One of those two would cause these errors... No such file or directory

**Comment by corbinlc** [comment]
To get a working session, what did you have to do?  Just click on the session again, or uninstall and reinstall or ?

**Comment by keaneokelley** [comment]
Honestly, I have no idea why it started working. I did reinstall the app several times (also through Android Studio) and I had the same problem. One time, I commented out the line (97 in DownloadUtility) that performs deletion of the existing file before downloading, and it worked. So I put the line back, deleted the app, reinstalled, and it still works. 

Now it seems to work in all cases.

**Comment by AdamMatthewLTM** [comment]
@keaneokelley ,

Thank you for filing this issue. At the moment I am unable to replicate your problem with the latest build of UserLAnd, however **I can confirm this issue was replicated during a previous build.** I understand the application is now working for you - but I will recommend this issue remain open for a period of time if others are able to replicate it with the current build version.

In case this issue is run into by others, I will provide a short list of steps taken that eventually resulted in the hanging downloads status circle to function correctly.

1) The code was pulled via git from the github repo on Windows 10 and cloned into an appropriate directory
2) After the build and installation steps in the latest version of Android Studio (3.1.3) the progress indication seemed to hang indefinitely.
3) In Android Studio, under the 'build' tag Clean Project and Rebuild Project were selected consecutively. This failed to fix the issue.
4) The cloned git folder was manually deleted and re-downloaded. UserLAnd was rebuilt in Studio.
5) In Android Studio, Clean Project and Rebuild Projected were selected consecutively again. 

**This final 5th step** resulted in the application installation working correctly and no longer hanging indefinitely at the downloading progress indicator. 

If anyone runs into this issue and can replicate the same (or a different method) of fixing it please reply to this thread and confirm that you have done so.

Thank you,
-Adam

**Comment by corbinlc** [comment]
I am guessing it is a luck thing right now.  There is something we are not managing correctly with our flow for downloading files and moving them.  While it generally works, it must not always work.  We will have to see what we can do the replicate it.  Since @AdamMatthewLTM  has seen it and he on onurthe team, maybe we can have him loop on this and see what additional tidbits we can learn.

**Comment by AdamMatthewLTM** [comment]
@Grunthos and @k3an3 ,

As a follow-up to this could you please let me know if this is still an issue for both of you with the latest UerLAnd version? Thanks for your time,

-Adam
