### ISSUE TITLE
Help - [Assistance Needed With InstaPy]

### ISSUE THREAD

**Issue by Areahints** [CypherpunkArmory/UserLAnd#688]
# Describe the issue you are having.

I am trying to install [InstaPy](https://github.com/timgrossmann/InstaPy) however i am running into a few snags due to lack of understanding of how ubuntu-userland works

The Installation instructions is

`pip install instapy`

After this, I should be able to run some scripts

This is what I've done with Userland

```
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install python3 binutils binfmt-support python3 apt-utils whiptail nano cron build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip git python3-dev libffi-dev xvfb wget locales g++ make software-properties-common openssh-client iputils-ping net-tools iproute2
```

set my alias

```
nano ~/.bashrc
alias python='python3.6'
. ~/.bashrc
```

Install pip

```
wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py
python get-pip.py

```
Set Time Zone

`dpkg-reconfigure tzdata `

 running `uname -a` outputs
```
Linux localhost 3.4.0-CAF #1 SMP PREEMPT Mon Jan 23 12:21:30 UTC 2017 armv7l armv7l armv7l GNU/Linux
```

At this point I then switched to the guide found [here](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md)

```
pip install --user instapy
pip uninstall instapy-chromedriver
pip install instapy-chromedriver==2.36.post0
mkdir InstaPy
cd InstaPy
```

I have copied my script `area.py` into InstaPy

`python area.py` gave me

```
INFO [2019-03-12 16:22:28] [------]  Using built in instapy-chromedriver executable (version 2.36.post0)
ERROR [2019-03-12 16:23:33] ------]  Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 3.4.0-CAF armv7l)
Traceback (most recent call last):
  File "/home/kc/.local/lib/python3.6/site-packages/instapy/browser.py", line 142, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 3.4.0-CAF armv7l)

Traceback (most recent call last):
  File "area.py", line 18, in <module>
    session = InstaPy(username='------', password='------', headless_browser=True, nogui=True)
  File "/home/kc/.local/lib/python3.6/site-packages/instapy/instapy.py", line 288, in __init__
    self.set_selenium_local_session()
  File "/home/kc/.local/lib/python3.6/site-packages/instapy/instapy.py", line 342, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.6/dist-packages/instapy_chromedriver/chromedriver
```
I then decide to check if Chromium Browser is accesible via Terminal 
```
$ chromium-browser
Segmentation fault
```
A quick duckduckgo reveals thats 

> A segmentation fault will occur, for example, if a program attempts to access memory that does not belong to it; then the kernel brings a hammer down. This is the result of a programming error.
> 
> It should absolutely unequivocally not be possible for you to force an end-user tool to do this, regardless of how you have used it. So that would be a bonefide bug, and you should report it.

[source](https://raspberrypi.stackexchange.com/questions/5290/chromium-segmentation-fault-error/5301)

So i try `sudo chromium-browser` and it gives me no errors

i then cd into InstaPy and run `sudo xvfb-run python area.py` and thats where ive been stuck at ever since

the terminal doesnt give me any sort of info, either error or otherwise

i've left it for an hour now hoping at least that i could check if the script truly ran by accessing the instagram account and checking for interactions but it isnt working

ps-a shows that sudo is running but thats its , no way for me to see what going on

# Describe how your task behaves in a regular Linux environment

on a normal linux installation the command `python area.py` will output information on the terminal about what it is doing based on the settings in the script
 and as long as i set headless_browser=True, nogui=True and have xvfb installed, it should only need a teminal

I would appreciate any help immensely

**Comment by Areahints** [comment]
abandoning this because the issue stems from the architecture of the phone (ARM32).
